# Generated by Django 4.0.4 on 2022-05-07 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Location of the file', max_length=200)),
                ('content', models.TextField(help_text='Content of the file')),
                ('MMIE', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/html', 'HTML'), ('text/css', 'CSS'), ('text/javascript', 'Javascript')], default='text/plain', help_text="MMIE of the file, choose Plain Text if you don't know what to do", max_length=200)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
