# Generated by Django 4.0.4 on 2022-05-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='id',
        ),
        migrations.AlterField(
            model_name='text',
            name='location',
            field=models.CharField(help_text='Location of the file', max_length=200, primary_key=True, serialize=False),
        ),
    ]
