# Generated by Django 4.0.4 on 2022-05-07 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_remove_text_id_alter_text_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='creator',
            field=models.ForeignKey(help_text='The owner of this text', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
