# Generated by Django 4.0.4 on 2022-05-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_text_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='b64',
            field=models.BooleanField(default=True, help_text='If yes, the content will be treated as base64.'),
        ),
        migrations.AlterField(
            model_name='text',
            name='MMIE',
            field=models.CharField(default='text/plain', help_text="MMIE of the file, choose text/plain if you don't know what to do", max_length=200),
        ),
    ]
