# Generated by Django 4.0.4 on 2022-05-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_text_b64_alter_text_mmie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(help_text='Content of the file', max_length=40000),
        ),
    ]
